@baseUrl = http://localhost:5001/api/v1
###

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "u2.l@mail.com",
  "password": "password1aB"
}

###

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "u1.l@mail.com",
  "password": "password1aB"
}
