version: "3.9"
services:
  todo-api:
    container_name: todo-api
    build:
      context: ./todo-api
      dockerfile: Dockerfile.dev
    ports:
      - ${TODO_API_PORT}:3000
    volumes: 
      - ./todo-api:/app
      - /app/node_modules
    depends_on:
      - todo-db
    environment:
      TODO_DB_POSTGRES_DATABASE: ${TODO_DB_POSTGRES_DATABASE}
      TODO_DB_POSTGRES_USER: ${TODO_DB_POSTGRES_USER}
      TODO_DB_POSTGRES_PASSWORD: ${TODO_DB_POSTGRES_PASSWORD}
      TODO_DB_POSTGRES_HOST: ${TODO_DB_POSTGRES_HOST}
      TODO_API_PORT: ${TODO_API_PORT}
      TODO_API_PREFIX: ${TODO_API_PREFIX}
      TODO_FE_HOST: ${TODO_FE_HOST}
      TODO_FE_PORT: ${TODO_FE_PORT}
      TODO_API_JWT_SECRET: ${TODO_API_JWT_SECRET}
  todo-fe:
    container_name: todo-fe
    build:
      context: ./todo-fe
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_TODO_API_BASE_URL: ${TODO_API_HOST}:${TODO_API_PORT}${TODO_API_PREFIX}
      REACT_APP_JWT_SECRET: ${TODO_API_JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-development}
    ports: 
      - ${TODO_FE_PORT}:3000
    volumes: 
      - ./todo-fe:/app
      - /app/node_modules
  todo-db:
    image: postgres:14
    container_name: todo-db
    environment:
      POSTGRES_DB: ${TODO_DB_POSTGRES_DATABASE}
      POSTGRES_USER: ${TODO_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TODO_DB_POSTGRES_PASSWORD}
    ports:
      - ${TODO_DB_POSTGRES_PORT}:5432
    volumes:
      - todo-db-data:/var/lib/postgresql/data:cached
volumes:
  todo-db-data:
    
