apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
spec:
  selector:
    app: todo-db
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: todo-db-container
        image: postgres:14
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: TODO_DB_POSTGRES_DATABASE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: TODO_DB_POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: TODO_DB_POSTGRES_PASSWORD
        volumeMounts:
        - name: todo-db-local
          mountPath: "/var/lib/postgresql/data"
        # - name: todo-db-aws-efs
        #   mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: todo-db-local
        persistentVolumeClaim:
          claimName: todo-pvc-local
      # - name: todo-db-aws-efs
      #   persistentVolumeClaim:
      #     claimName: todo-db-pvc-aws-efs