apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  selector:
    app: todo-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api-container
          image: imanjamali/todo-api:latest
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: NODE_ENV
            - name: TODO_DB_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: TODO_DB_POSTGRES_DATABASE
            - name: TODO_DB_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: TODO_DB_POSTGRES_USER
            - name: TODO_DB_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: TODO_DB_POSTGRES_PASSWORD
            - name: TODO_DB_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: TODO_DB_POSTGRES_HOST
            - name: TODO_API_PORT
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: TODO_API_PORT
            - name: TODO_API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: TODO_API_JWT_SECRET