apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv-local
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /todo-data
    type: DirectoryOrCreate