apiVersion: v1
kind: Secret
metadata:
  name: todo-fe-secret
  labels:
    app: todo-fe
type: Opaque
stringData:
  config.js: |-
    window["_env_"] =  {
      REACT_APP_TODO_API_BASE_URL: "https://todo-api-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com"
    }
