apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  labels:
    app: todo-api
type: Opaque
stringData:
  NODE_ENV: "production"
  TODO_API_PORT: "5001"
  TODO_API_JWT_SECRET: "topawesomesecret"
