apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  labels:
    app: todo-db
type: Opaque
stringData:
  TODO_DB_POSTGRES_USER: "todo-api-db-user"
  TODO_DB_POSTGRES_PASSWORD: todo-api-db-password"
  TODO_DB_POSTGRES_DATABASE: "todo-api-db"
  TODO_DB_POSTGRES_HOST: "todo-db-service"
