apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
  labels:
    app: todo-db
spec:
  selector:
    app: todo-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-deployment
  labels:
    app: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: todo-db-container
        image: registry.redhat.io/rhel9/postgresql-13
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: TODO_DB_POSTGRES_DATABASE
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: TODO_DB_POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: TODO_DB_POSTGRES_PASSWORD
        volumeMounts:
        - name: todo-db-volume
          mountPath: "/var/lib/pgsql/data"
      volumes:
      - name: todo-db-volume
        persistentVolumeClaim:
          claimName: todo-db-pvc