apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
type: Opaque
stringData:
  TODO_DB_POSTGRES_USER: ""
  TODO_DB_POSTGRES_PASSWORD: ""
  TODO_DB_POSTGRES_DATABASE: ""
  TODO_API_JWT_SECRET: ""
