apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
type: Opaque
stringData:
  TODO_DB_POSTGRES_USER: "postgres"
  TODO_DB_POSTGRES_PASSWORD: "postgres"
  TODO_DB_POSTGRES_DATABASE: "postgres"
